'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const os = require('node:os');
const { chromium } = require('playwright');
const { createApp } = require('../index');

(async () => {
  const dataDir = await fs.mkdtemp(path.join(os.tmpdir(), 'ticket4t-browser-'));
  const output = path.resolve('artifacts/screenshots');
  await fs.mkdir(output, { recursive: true });
  const runtime = await createApp({ env: { NODE_ENV: 'test', SEED_DEMO: 'true', SESSION_SECRET: 'ui-tests-only-'.repeat(5) }, dataDir, seedDays: 2, disableRateLimit: true });
  const server = runtime.app.listen(0, '127.0.0.1');
  await new Promise(resolve => server.once('listening', resolve));
  const base = 'http://127.0.0.1:' + server.address().port;
  const browser = await chromium.launch({ channel: process.env.BROWSER_CHANNEL || 'chrome', headless: true });
  const failures = [];
  async function instrument(page) {
    page.on('pageerror', error => failures.push(error.message));
    page.on('console', message => { if (message.type() === 'error' && /Content Security Policy|Refused to|Uncaught/i.test(message.text())) failures.push(message.text()); });
    page.on('response', response => {
      if (response.status() === 404 && !response.url().endsWith('/favicon.ico')) failures.push('404: ' + response.url());
    });
  }
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    await instrument(page);
    await page.goto(base);
    await page.locator('#search-form').waitFor();
    await page.evaluate(() => document.fonts.ready);
    assert.match(await page.locator('body').innerText(), /Dữ liệu minh họa/);
    await page.screenshot({ path: path.join(output, 'home-desktop.png'), fullPage: true });
    const bootstrap = await (await fetch(base + '/api/bootstrap')).json();
    const tomorrow = new Date(bootstrap.today + 'T12:00:00Z');
    tomorrow.setUTCDate(tomorrow.getUTCDate() + 1);
    const date = tomorrow.toISOString().slice(0, 10);
    await page.selectOption('#search-from', 'ho-chi-minh');
    await page.selectOption('#search-to', 'da-lat');
    await page.fill('#search-date', date);
    await page.locator('#search-form button[type="submit"]').click();
    await page.locator('.trip-card').first().waitFor();
    assert.equal(await page.locator('.trip-card').count(), 4);
    await page.selectOption('#sort-select', 'price');
    await page.waitForURL(/sort=price/);
    await page.locator('.trip-card').first().waitFor();
    await page.screenshot({ path: path.join(output, 'search-desktop.png'), fullPage: true });
    await page.locator('.trip-card .btn').first().click();
    await page.locator('button[data-action="seat"]:enabled').first().waitFor();
    await page.locator('button[data-action="seat"]:enabled').nth(0).click();
    await page.locator('button[data-action="seat"]:enabled').nth(1).click();
    await page.screenshot({ path: path.join(output, 'seats-desktop.png'), fullPage: true });
    await page.locator('[data-action="checkout"]').click();
    await page.locator('#checkout-form').waitFor();
    await page.fill('#fullName', 'Khách kiểm thử');
    await page.fill('#phone', '0912345678');
    await page.fill('#email', 'qa@example.com');
    await page.check('#checkout-form [name="consent"]');
    const bookingResponse = page.waitForResponse(response => response.url().endsWith('/api/bookings') && response.request().method() === 'POST');
    await page.click('#book-button');
    const created = await (await bookingResponse).json();
    assert.ok(created.booking?.code, JSON.stringify(created));
    assert.equal(created.booking.paymentStatus, 'pending');
    assert.equal(created.booking.seats.length, 2);
    await page.locator('[data-action="print"]').waitFor();
    await page.screenshot({ path: path.join(output, 'ticket-desktop.png'), fullPage: true });
    await page.goto(base + '/#/tickets');
    await page.locator('#lookup-form').waitFor();
    await page.fill('#lookup-form [name="code"]', created.booking.code);
    await page.fill('#lookup-form [name="phone"]', '0912345678');
    await page.locator('#lookup-form button[type="submit"]').click();
    await page.locator('[data-action="cancel-booking"]').waitFor();
    await page.locator('[data-action="cancel-booking"]').click();
    await page.click('#modal-confirm');
    await page.getByText('Đã hủy', { exact: true }).first().waitFor();
    const cancelled = await (await fetch(base + '/api/bookings/lookup?code=' + created.booking.code + '&phone=0912345678')).json();
    assert.equal(cancelled.booking.status, 'cancelled');
    for (const route of ['operators', 'support', 'login', 'register', 'forgot-password']) {
      await page.goto(base + '/#/' + route);
      await page.locator('#main h1').first().waitFor();
      assert.doesNotMatch(await page.locator('#main').innerText(), /Hành trình tạm gián đoạn|Chúng ta hơi lạc đường/);
    }
    await page.setViewportSize({ width: 390, height: 844 });
    await page.goto(base);
    await page.locator('#search-form').waitFor();
    await page.evaluate(() => document.fonts.ready);
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), 'Mobile page must fit the viewport.');
    await page.screenshot({ path: path.join(output, 'home-mobile.png'), fullPage: true });

    const admin = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    await instrument(admin);
    await admin.goto(base + '/admin');
    await admin.fill('#login-form [name="email"]', 'admin@ticket4t.vn');
    await admin.fill('#login-form [name="password"]', 'Admin@12345');
    await admin.locator('#login-form button[type="submit"]').click();
    await admin.locator('#portal').waitFor({ state: 'visible' });
    await admin.locator('.stat-card').first().waitFor();
    await admin.screenshot({ path: path.join(output, 'admin-desktop.png'), fullPage: true });
    for (const route of ['trips', 'operators', 'bookings', 'import', 'users']) {
      await admin.locator(`[data-page="${route}"]`).first().click();
      await admin.waitForFunction(() => !document.querySelector('#content .loading-panel, #content .loading-state'));
      await admin.locator('#content').waitFor();
      assert.doesNotMatch(await admin.locator('#content').innerText(), /Có lỗi hệ thống|Không thể tải|không có quyền/i);
    }
    await admin.locator('[data-page="operators"]').first().click();
    await admin.locator('[data-action="new-operator"]').click();
    await admin.fill('#editor-form [name="name"]', 'Nhà xe kiểm thử giao diện');
    await admin.fill('#editor-form [name="phone"]', '0912345678');
    await admin.fill('#editor-form [name="email"]', 'operator@example.com');
    const operatorResponse = admin.waitForResponse(response => response.url().endsWith('/api/admin/operators') && response.request().method() === 'POST');
    await admin.locator('#editor-form button[type="submit"]').click();
    const operatorCreated = await (await operatorResponse).json();
    assert.ok(operatorCreated.operator?.id, JSON.stringify(operatorCreated));
    await admin.locator('#editor-dialog').waitFor({ state: 'hidden' });
    await admin.locator('[data-page="trips"]').first().click();
    await admin.locator('[data-action="new-trip"]').click();
    await admin.selectOption('#editor-form [name="operatorId"]', operatorCreated.operator.id);
    await admin.selectOption('#editor-form [name="type"]', 'limousine');
    await admin.selectOption('#editor-form [name="from"]', 'ho-chi-minh');
    await admin.selectOption('#editor-form [name="to"]', 'da-lat');
    await admin.fill('#editor-form [name="date"]', date);
    await admin.fill('#editor-form [name="departureTime"]', '18:00');
    await admin.fill('#editor-form [name="durationMinutes"]', '360');
    await admin.fill('#editor-form [name="totalSeats"]', '9');
    await admin.fill('#editor-form [name="pickupPoints"]', 'Điểm đón kiểm thử');
    await admin.fill('#editor-form [name="dropoffPoints"]', 'Điểm trả kiểm thử');
    await admin.fill('#editor-form [name="provenance"]', 'Kho vé giả lập dành riêng cho kiểm thử tự động giao diện');
    const tripResponse = admin.waitForResponse(response => response.url().endsWith('/api/admin/trips') && response.request().method() === 'POST');
    await admin.locator('#editor-form button[type="submit"]').click();
    const managedTrip = await (await tripResponse).json();
    assert.equal(managedTrip.trip?.source, 'managed', JSON.stringify(managedTrip));
    await admin.locator('#editor-dialog').waitFor({ state: 'hidden' });
    await page.goto(base + '/#/trip/' + managedTrip.trip.id);
    await page.locator('button[data-action="seat"]:enabled').first().click();
    await page.locator('[data-action="checkout"]').click();
    await page.locator('#checkout-form').waitFor();
    await page.fill('#fullName', 'Khách kiểm thử hoàn tiền');
    await page.fill('#phone', '0912345678');
    await page.fill('#email', 'refund-qa@example.com');
    await page.check('#checkout-form [name="consent"]');
    const managedBookingResponse = page.waitForResponse(response => response.url().endsWith('/api/bookings') && response.request().method() === 'POST');
    await page.click('#book-button');
    const managedBooking = await (await managedBookingResponse).json();
    assert.ok(managedBooking.booking?.code, JSON.stringify(managedBooking));
    await page.locator('[data-action="print"]').waitFor();
    await admin.locator('[data-page="bookings"]').first().click();
    await admin.locator(`[data-action="cash-receipt"][data-id="${managedBooking.booking.code}"]`).click();
    await admin.fill('#editor-form [name="reference"]', 'QA-CASH-' + Date.now());
    const cashResponse = admin.waitForResponse(response => response.url().endsWith('/cash-receipt'));
    await admin.locator('#editor-form button[type="submit"]').click();
    const paidBooking = await (await cashResponse).json();
    assert.equal(paidBooking.booking?.paymentStatus, 'paid', JSON.stringify(paidBooking));
    await admin.locator('#editor-dialog').waitFor({ state: 'hidden' });
    await page.reload();
    await page.locator('[data-action="cancel-booking"]').click();
    await page.click('#modal-confirm');
    await page.getByText('Chờ hoàn tiền', { exact: true }).first().waitFor();
    await admin.locator('[data-action="refresh"]').first().click();
    await admin.locator(`[data-action="refund-receipt"][data-id="${managedBooking.booking.code}"]`).click();
    await admin.fill('#editor-form [name="reference"]', 'QA-REFUND-' + Date.now());
    await admin.check('#editor-form [name="receiptConfirmed"]');
    const refundResponse = admin.waitForResponse(response => response.url().endsWith('/refund-receipt'));
    await admin.locator('#editor-form button[type="submit"]').click();
    const refundedBooking = await (await refundResponse).json();
    assert.equal(refundedBooking.booking?.paymentStatus, 'refunded', JSON.stringify(refundedBooking));
    await admin.locator('#editor-dialog').waitFor({ state: 'hidden' });
    await page.reload();
    await page.getByText('Đã hoàn tiền', { exact: true }).first().waitFor();
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), 'Mobile receipt must fit the viewport.');
    await page.screenshot({ path: path.join(output, 'ticket-mobile.png'), fullPage: true });
    await admin.setViewportSize({ width: 390, height: 844 });
    await admin.locator('[data-page="dashboard"]').first().click({ force: true });
    assert.ok(await admin.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), 'Mobile admin must fit the viewport.');
    await admin.screenshot({ path: path.join(output, 'admin-mobile.png'), fullPage: true });
    assert.deepEqual(failures, [], 'No missing app resources, browser crashes or CSP errors.');
    console.log('Browser checks passed: search, seats, checkout, lookup, cancellation, public routes, mobile, admin pages, operator/trip creation, cash receipts and refund receipts.');
    console.log('Screenshots:', output);
  } finally {
    await browser.close();
    await new Promise(resolve => server.close(resolve));
    await runtime.close();
    const cleanupTarget = path.resolve(dataDir);
    const tempRoot = path.resolve(os.tmpdir()) + path.sep;
    if (!cleanupTarget.startsWith(tempRoot) || !path.basename(cleanupTarget).startsWith('ticket4t-browser-')) throw new Error('Invalid temporary cleanup path.');
    await fs.rm(cleanupTarget, { recursive: true, force: true });
  }
})().catch(error => { console.error(error); process.exitCode = 1; });
